BEGIN TRANSACTION;
CREATE TABLE `title` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`title`	TEXT NOT NULL,
	`artist`	INTEGER NOT NULL,
	`duration`	INTEGER
);
CREATE TABLE `sender` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`name`	INTEGER NOT NULL UNIQUE
);
CREATE TABLE `playlist` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`sender_id`	INTEGER NOT NULL,
	`title_id`	INTEGER NOT NULL,
	`date`	INTEGER NOT NULL,
	`time`	INTEGER NOT NULL
);
CREATE TABLE `artist` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`artist`	TEXT NOT NULL
);
;
COMMIT;
